name: YearProgressBot

on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkouts
         uses: actions/checkout@v2

       - name: Setup Configs
         run: |
              source config.txt
              GIT_EMAIL="${{ secrets.GIT_EMAIL }}"
              TG_TOKEN="${{ secrets.TG_TOKEN }}"
              GIT_TOKEN="${{ secrets.GIT_TOKEN }}"
              GIT_USERNAME="${{ secrets.GIT_USERNAME }}"
              if [[ "${TG_TOKEN}" == "" ]]; then echo 'TG Token not set, Exiting...' && exit 1 ; fi
              if [[ "${GIT_TOKEN}" == "" ]]; then echo 'GIT Token not set, Exiting...' && exit 1 ; fi
              if [[ "${GIT_USERNAME}" == "" ]]; then echo 'GIT Username not set, Exiting...' && exit 1 ; fi
              if [[ "${GIT_EMAIL}" == "" ]]; then echo 'GIT Email not set, Exiting...' && exit 1 ; fi
              export GIT_NAME_AND_REPONAME=$(git config --get remote.origin.url | sed 's/.*\/\([^ ]*\/[^.]*\).*/\1/')
              export GITHUB_USERNAME=$(echo "${GIT_NAME_AND_REPONAME}" | sed 's/\/.*//')
              echo $GIT_NAME_AND_REPONAME
              git config --global user.email "${GIT_EMAIL}"
              git config --global user.name "${GIT_USERNAME}"
              bash bot.sh

       - name: Run YearProgressBot
         run: |
              bash bot.sh

